name: Continuous integration
#on: [pull_request, push]
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      triggerIos:
        description: 'Run iOS tests'
        required: true
        default: 'no'
      triggerMacos:
        description: 'Run macOS tests'
        required: true
        default: 'no'
      trigger3DS:
        description: 'Run 3DS tests'
        required: true
        default: 'no'
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: numworks/setup-emscripten@master
        with:
          sdk: 1.40.1
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: make PLATFORM=simulator TARGET=web ./output/release/simulator/web/apps/i18n.cpp
      - run: make -j2 PLATFORM=simulator TARGET=web EPSILON_APPS=code
      - run: npm install uglify-js -g
      - run: uglifyjs ./output/release/simulator/web/epsilon.js -o epsilon.python.min.js -cm 
      - id: 'auth'
        #if: ${{ github.event_name == 'push' && github.ref_name == 'upsilon-dev' && github.repository == 'UpsilonNumworks/Upsilon' }}
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{secrets.GOOGLE_CREDENTIALS}}'
      - id: 'upload-file'
        #if: ${{ github.event_name == 'push' && github.ref_name == 'upsilon-dev' && github.repository == 'UpsilonNumworks/Upsilon' }}
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'epsilon.python.min.js'
          destination: 'upsilon-binfiles.appspot.com/official/simulator/'
          parent: false
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-web.zip
          path: output/release/simulator/web/epsilon.zip
env:
  ACCEPT_OFFICIAL_TOS: 1
