name: Continuous integration
#on: [pull_request, push]
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      triggerIos:
        description: 'Run iOS tests'
        required: true
        default: 'no'
      triggerMacos:
        description: 'Run macOS tests'
        required: true
        default: 'no'
      trigger3DS:
        description: 'Run 3DS tests'
        required: true
        default: 'no'
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: numworks/setup-emscripten@master
        with:
          sdk: 1.40.1
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: make PLATFORM=simulator TARGET=web ./output/release/simulator/web/apps/i18n.cpp
      - run: make -j2 PLATFORM=simulator TARGET=web EPSILON_APPS=code
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-web.zip
          path: output/release/simulator/web/epsilon.zip
env:
  ACCEPT_OFFICIAL_TOS: 1
